namespace HidWin.Enums;

internal enum WinError : int
{
    ERROR_NO_FUNCTION = 1,
    ERROR_IO_PENDING = 997,
    ERROR_OPERATION_ABORTED = 995,
    ERROR_HANDLE_EOF = 38,
    ERROR_NO_MORE_ITEMS = 122,
    ERROR_INSUFFICIENT_BUFFER = 259,
    ERROR_GEN_FAILURE = 31

}

